### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/BEAT/beat_cache/beat_4english_15_141/weights/GesAxisAngle_Face_300.bin'

### ISSUE THREAD

**Issue by ggg66** [JeremyCJM/DiffSHEG#4]

**Comment by JeremyCJM** [comment]
The "GesAxisAngle_Face_300.bin" is an autoencoder checkpoint for computing the Frechet Distance metrics. I will upload the autoencoder checkpoints later. You can temporally comment them out without computing Frechet Distance metrics during training.

**Comment by ggg66** [comment]
Thank you for your response, but there are still many files that show "FileNotFoundError," for example 
Traceback (most recent call last):
  File "/root/miniconda3/envs/diffsheg/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/autodl-tmp/DiffSHEG/runner.py", line 301, in main_worker
    val_dataset = __import__(f"datasets.{opt.dataset_name}", fromlist=["something"]).BeatDataset(opt, "val")
  File "/root/autodl-tmp/DiffSHEG/datasets/beat.py", line 112, in __init__
    self.build_cache(preloaded_dir)
  File "/root/autodl-tmp/DiffSHEG/datasets/beat.py", line 140, in build_cache
    self.cache_generation(
  File "/root/autodl-tmp/DiffSHEG/datasets/beat.py", line 154, in cache_generation
    dst_lmdb_env = lmdb.open(out_lmdb_dir, map_size=map_size)
FileNotFoundError: [Errno 2] No such file or directory: 'data/BEAT/beat_cache/beat_4english_15_141/val/bvh_rot_cache_len34_stride10'

**Comment by JeremyCJM** [comment]
Please kindly refer to https://github.com/JeremyCJM/DiffSHEG/issues/1#issuecomment-2073909211 and https://github.com/JeremyCJM/DiffSHEG/issues/2#issuecomment-2085595280.
